In [22]:
import os
import numpy as np
from PIL import Image

# your dataset path
dataset_path = "C:\\xampp\\htdocs\\Evala\\ReColor\\ReColor-Backend\\color_dataset_rgb_hsv"
color_families = ['red', 'green', 'blue']

dataset_pixels = []
labels = []

for color_name in color_families:
    folder_path = os.path.join(dataset_path, color_name)
    for file in os.listdir(folder_path):
        img_path = os.path.join(folder_path, file)
        img = Image.open(img_path).convert("RGB").resize((32, 32))
        pixels = np.array(img).reshape(-1, 3)  # flatten pixels
        dataset_pixels.append(pixels)
        labels.extend([color_name] * len(pixels))

dataset_pixels = np.vstack(dataset_pixels)  # combine all pixels
print("✅ Dataset pixel array shape:", dataset_pixels.shape)


✅ Dataset pixel array shape: (3072000, 3)


In [25]:
from sklearn.cluster import KMeans

k = 3
kmeans = KMeans(n_clusters=10, random_state=42)
kmeans.fit(dataset_pixels)
print("✅ K-Means centroids:\n", kmeans.cluster_centers_.astype(int))   

✅ K-Means centroids:
 [[ 38 193  38]
 [109 109 204]
 [ 26  28  27]
 [202 105 105]
 [110 209 110]
 [ 38  38 112]
 [208  36  36]
 [ 39 112  39]
 [111  37  38]
 [ 41  40 203]]
